import fs from "fs";
import path from "path";
import os from "os";
import { getAnchor, getDigest } from "./db";
import { getClassification } from "./classifier";
import type { SessionMeta } from "./types";

const VAULT_DIR = path.join(
  os.homedir(),
  "Desktop",
  "obsidian",
  "my working",
  "daily-logs"
);

function safeFilename(s: string): string {
  return s.replace(/[^A-Za-z0-9_\-]/g, "_").slice(0, 60);
}

function fmtTokens(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(2) + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1) + "k";
  return String(n);
}

/**
 * Write a session digest to Obsidian's daily-logs as a durable note.
 * Called on snapshot or session end.
 */
export function exportSessionToObsidian(session: SessionMeta): {
  ok: boolean;
  filepath?: string;
  error?: string;
} {
  try {
    if (!fs.existsSync(VAULT_DIR)) {
      return { ok: false, error: "vault dir not found: " + VAULT_DIR };
    }
    const anchor = getAnchor(session.sessionId);
    const digest = getDigest(session.sessionId);
    const classification = getClassification(session.sessionId);

    const dateStr = new Date()
      .toISOString()
      .slice(0, 10)
      .replace(/-/g, "");
    const filename = `${dateStr}-agent-os-${safeFilename(session.projectName)}-${session.sessionId.slice(0, 8)}.md`;
    const filepath = path.join(VAULT_DIR, filename);

    const totals = session.tokensThisWindow;
    const role = classification?.role;
    const focus = classification?.focus;

    const md = `---
compiled: false
source: agent-os
session_id: ${session.sessionId}
project: ${session.projectName}
cwd: ${session.cwd}
captured_at: ${new Date().toISOString()}
role: ${role ?? "unknown"}
---

# ${session.projectName} — ${focus ?? role ?? "session"}

**Session ID:** \`${session.sessionId}\`
**Working dir:** \`${session.cwd}\`
**Role:** ${role ?? "unclassified"}${focus ? ` · ${focus}` : ""}
**Captured:** ${new Date().toLocaleString()}

## Goal
${anchor?.text ?? "(no goal set)"}

## Digest
${digest?.digestText ?? "(no digest available)"}

${digest?.goalAlignment ? `**Alignment:** ${digest.goalAlignment}` : ""}

## Tokens this 5h window
- Input: ${fmtTokens(totals.input)}
- Output: ${fmtTokens(totals.output)}
- Cache create: ${fmtTokens(totals.cacheCreate)}
- Cache read: ${fmtTokens(totals.cacheRead)}

## Last activity
${session.lastSummary || "(no summary)"}

---
_Generated by Agent OS on ${new Date().toISOString()}_
`;

    fs.writeFileSync(filepath, md, "utf8");
    return { ok: true, filepath };
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : "export failed",
    };
  }
}
